name: shift_app
description: shift_app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # 就係要加返呢個範圍

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  intl: ^0.19.0
  url_launcher: ^6.3.2
  timezone: ^0.11.0
  permission_handler: ^11.4.0
  android_intent_plus: ^4.0.0
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/holidays/hk_holidays_2026.json