name: shift_app
description: shift_app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  timezone: ^0.9.0
  # 強制使用這個版本，避開 Windows 依賴問題
  permission_handler: ^12.0.1
  android_intent_plus: ^6.0.0
  device_info_plus: ^13.1.0
  device_calendar: ^4.3.3
  path_provider: ^2.1.2
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/holidays/hk_holidays_2026.json
